//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyFund.DataContracts.DataModel
{
    using System;
    
    public partial class GetUsersByAdminID_Result2
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> CurrentAmount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
