//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyFund.DataContracts.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransectionDetail
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> CurrentAmount { get; set; }
        public Nullable<decimal> TransectionAmount { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
